### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by morelife09** [morelife09/chat-space#10]
# IPアドレス
176.32.69.240

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◎自動更新ができない**
自動更新の挙動が確認できませんでした。
自動更新ができるようにしましょう



参考カリキュラム：https://master.tech-camp.in/curriculums/1211

**◎ビューの崩れ**
◯サイドバーの文字の位置と大きさを仕様書通りにしましょう
仕様書を確認し、色やpadding,marginのpx数の値を修正しましょう
- グループ名の表示位置
- ラストメッセージの表示位置
- それぞれの文字の大きさと色

![非同期通信画面](https://user-images.githubusercontent.com/44963290/85485306-6e4e3e00-b603-11ea-8472-82b8e8704b5e.png)



お手本

<img width="1439" alt="ChatSpace" src="https://user-images.githubusercontent.com/44963290/85384860-8b8bf980-b57c-11ea-92eb-cfddd844094a.png">




参考カリキュラム:https://master.tech-camp.in/curriculums/3944

<img width="837" alt="サイドバー" src="https://user-images.githubusercontent.com/44963290/83826704-85da8b00-a717-11ea-92ef-5d45964baf93.png">





修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！
